server:
    port: 8701

eureka:
  client:
    healthcheck: true 
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://114.70.193.179:8761}/eureka/
    instance:
      statusPageUrlPath: https://${eureka.hostname}/info
      healthCheckUrlPath: https://${eureka.hostname}/health
      homePageUrl: https://${eurkea.hostname}/
    preferIpAddress: true

