server:
    port: 8766
    
spring:
    application:
        name: sharing-service-sidecar
      
sidecar:
    port: 3000
    health-uri: http://114.70.193.179:3000/sharing/health
 
eureka:
  client:
    healthcheck: true 
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://114.70.193.179:8761}/eureka/
    instance:
      statusPageUrlPath: https://${eureka.hostname}/info
      healthCheckUrlPath: https://${eureka.hostname}/health
      homePageUrl: https://${eurkea.hostname}/
    preferIpAddress: true
